apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    jsonData:
      tlsSkipVerify: false
    version: 1
    editable: true
